const PHASE_CODE = require('./PHASE_CODE.js');
var PHASE_LIST = [
  PHASE_CODE.DAY,
  PHASE_CODE.NIGHTCOMING,
  PHASE_CODE.WEREWOLF,
  PHASE_CODE.SAVIOR,
  PHASE_CODE.WITCH,
  PHASE_CODE.SEER,
  //PHASE_CODE.HUNZI,
  PHASE_CODE.SUNRAISE,
];

module.exports = PHASE_LIST;
